
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: helm-rocket-app
        image: dockerhub1010/helm-rockets:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-app-service
spec:
  type: NodePort
  selector:
    app: devops-project
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
